#!/usr/bin/make -f

image=kodi
namespace=crashvb
tag=SNAPSHOT
name=$(image)-$(tag)

buildargs=--build-arg=org_opencontainers_image_created="$(shell date '+%Y%m%d%H%M')" \
	--build-arg=org_opencontainers_image_revision="$(shell git rev-parse --short=12 --verify HEAD)"

dbtag=202210261444

dbrunargs=--env=MYSQL_DATABASE=kodi \
	--env=MYSQL_USER=kodi \
	--env=MYSQL_USER_PASSWORD=kodi
